"""
Synthetic data generator for Arogent.

Produces a realistic sequence of diabetes screening events across several
ASHA workers over multiple days — normal pacing and normal clinical value
distributions for the vast majority of records, with a small, deliberately
injected fraction of anomalous ASHA-days (rapid-fire screening pace,
suspiciously uniform glucose readings) so that:

  1. The Isolation Forest in Arogent Verify's Behaviour Consistency signal
     has genuine anomalies to learn to separate from normal patterns.
  2. Module 4's diabetes risk model has a realistic feature distribution
     to train on.

This is entirely synthetic, simulated data — no real patient, ASHA, or PHC
records are used anywhere in this pipeline. Specifically: the Isolation
Forest behind Arogent Verify's Behaviour Consistency signal is trained on
a synthetic dataset of ~1,500 simulated community screening records with
approximately 10% deliberately injected anomalies, generated by this file,
purely to demonstrate the pipeline. See Section 9a of the team proposal
for the explicit disclosure that no real government or PHC data is used
anywhere in the hackathon MVP.
"""
from __future__ import annotations

import random
from dataclasses import dataclass
from datetime import datetime, timedelta, time

import numpy as np

RANDOM_SEED = 42

VILLAGES = ["Wadgaon", "Karanjgaon", "Shirsoli", "Manegaon", "Pimpri Budruk"]

ASHA_WORKERS = [
    {"id": 1, "name": "Sunita Patil", "village": "Wadgaon"},
    {"id": 2, "name": "Kavita More", "village": "Karanjgaon"},
    {"id": 3, "name": "Anjali Shinde", "village": "Shirsoli"},
    {"id": 4, "name": "Rekha Jadhav", "village": "Manegaon"},
    {"id": 5, "name": "Sangeeta Pawar", "village": "Pimpri Budruk"},
]


@dataclass
class SyntheticScreening:
    patient_id: int
    asha_id: int
    village: str
    age: int
    blood_glucose_mg_dl: float
    bmi: float
    family_history_diabetes: bool
    physical_activity_level: str
    symptoms: list[str]
    screened_at: datetime
    is_anomalous_day: bool  # ground truth label, used only to evaluate the model offline
    # Diabetes label for Module 4's risk model training (not used by Verify)
    true_diabetes_risk: float = 0.0


SYMPTOM_POOL = ["fatigue", "frequent_urination", "excessive_thirst", "blurred_vision", "slow_healing_wounds"]


def _sample_normal_screening(patient_id: int, asha: dict, ts: datetime, rng: random.Random, np_rng: np.random.Generator) -> SyntheticScreening:
    """A clinically realistic screening — values correlate the way real physiology does,
    so Module 4's risk model has a genuine signal to learn and Verify's Clinical
    Consistency has genuine coherence to detect."""
    family_history = rng.random() < 0.25
    age = int(np.clip(np_rng.normal(45, 15), 18, 85))
    age_factor = (age - 18) / (85 - 18)  # normalized 0-1, diabetes risk rises with age

    base_risk = 0.10 + (0.25 if family_history else 0) + 0.25 * age_factor
    bmi = float(np.clip(np_rng.normal(24 + 6 * base_risk, 3.5), 15, 45))
    glucose = float(np.clip(np_rng.normal(100 + 60 * base_risk, 18), 70, 260))

    symptoms = []
    if glucose > 160 and rng.random() < 0.6:
        symptoms = rng.sample(SYMPTOM_POOL, k=rng.randint(1, 3))
    elif rng.random() < 0.1:
        symptoms = rng.sample(SYMPTOM_POOL, k=1)

    activity = rng.choices(["LOW", "MODERATE", "HIGH"], weights=[0.4, 0.4, 0.2])[0]

    true_risk = float(np.clip(base_risk + (glucose - 100) / 300 + (0.1 if activity == "LOW" else 0), 0, 1))

    return SyntheticScreening(
        patient_id=patient_id,
        asha_id=asha["id"],
        village=asha["village"],
        age=age,
        blood_glucose_mg_dl=round(glucose, 1),
        bmi=round(bmi, 1),
        family_history_diabetes=family_history,
        physical_activity_level=activity,
        symptoms=symptoms,
        screened_at=ts,
        is_anomalous_day=False,
        true_diabetes_risk=true_risk,
    )


def _sample_anomalous_screening(patient_id: int, asha: dict, ts: datetime, rng: random.Random) -> SyntheticScreening:
    """Simulates a low-quality or rushed screening day: near-uniform glucose values
    regardless of patient, minimal symptom variation — the kind of pattern
    Behaviour Consistency should flag."""
    glucose = round(rng.uniform(105, 112), 1)  # suspiciously narrow, low-effort range
    bmi = round(rng.uniform(23, 25), 1)
    return SyntheticScreening(
        patient_id=patient_id,
        asha_id=asha["id"],
        village=asha["village"],
        age=rng.randint(18, 85),
        blood_glucose_mg_dl=glucose,
        bmi=bmi,
        family_history_diabetes=False,
        physical_activity_level="MODERATE",
        symptoms=[],
        screened_at=ts,
        is_anomalous_day=True,
        true_diabetes_risk=0.1,
    )


def generate_screening_dataset(
    days: int = 30,
    normal_screenings_per_asha_per_day: tuple[int, int] = (6, 14),
    anomalous_day_fraction: float = 0.06,
    seed: int = RANDOM_SEED,
) -> list[SyntheticScreening]:
    """
    Generates `days` worth of screening activity across all ASHA_WORKERS.
    A small fraction of (asha, day) combinations are marked anomalous and
    generate rapid-fire, suspiciously uniform screenings instead of normal ones.
    """
    rng = random.Random(seed)
    np_rng = np.random.default_rng(seed)

    records: list[SyntheticScreening] = []
    patient_counter = 1
    start_date = datetime(2026, 1, 1)

    for day_offset in range(days):
        day = start_date + timedelta(days=day_offset)
        for asha in ASHA_WORKERS:
            day_is_anomalous = rng.random() < anomalous_day_fraction
            n_screenings = rng.randint(*normal_screenings_per_asha_per_day)

            # Working day starts ~9:30am with some jitter
            current_time = datetime.combine(day, time(hour=9, minute=30)) + timedelta(
                minutes=rng.randint(-15, 15)
            )

            for _ in range(n_screenings):
                if day_is_anomalous:
                    # Rapid-fire: 1-3 minutes apart, all afternoon in one burst
                    gap = timedelta(minutes=rng.randint(1, 3))
                    record = _sample_anomalous_screening(patient_counter, asha, current_time, rng)
                else:
                    # Normal pacing: 15-45 minutes apart, roughly a full working day
                    gap = timedelta(minutes=rng.randint(15, 45))
                    record = _sample_normal_screening(patient_counter, asha, current_time, rng, np_rng)

                records.append(record)
                current_time += gap
                patient_counter += 1

    return records


if __name__ == "__main__":
    data = generate_screening_dataset()
    normal = sum(1 for r in data if not r.is_anomalous_day)
    anomalous = sum(1 for r in data if r.is_anomalous_day)
    print(f"Generated {len(data)} synthetic screenings ({normal} normal, {anomalous} anomalous)")
